import { build, files, prerendered, version } from '$service-worker';
//build: An array of URL strings representing the files generated by Vite, suitable for caching with cache.addAll(build)
//files: An array of URL strings representing the files in your static directory
//prerendered: An array of pathnames corresponding to prerendered pages and endpoints.